# Setup
title: DevLOG_HJ
description: Studying hard to be a better developer.
url: https://Hyunjoon83.github.io/
avatar: /banana.jpg
paginate: 5
permalink: pretty
cover_image: /dub.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Hyunjoon Park
  links:
    - https://instagram.com/hjpark_83
    - https://github.com/Hyunjoon83
    - https://www.linkedin.com/in/hyunjoon83/
google_site_verification: google0726652c61a38ae7.html
lang: en-US

sass:
  sass_dir: _sass
  style: :compressed

# Options
google_adsense: true
# Replace this value and uncomment to enable Google Analytics tracking
google_analytics: G-EJDQ9Z6XYN

# Replace this value and uncomment to enable Disqus
disqus: hyunjoon83-github-io

# Specify the author for blog posts
author:
  name: Hyunjoon Park
  url: https://github.com/Hyunjoon83/
  email: hyunjoonpark0803@gmail.com
